Adiciona Validacao dos funcionarios
viniciuslunardi/Trabalho01 pull request #3
Opened 2021-04-06 04:02 UTC by merciasm

2021-04-06 12:01 UTC, viniciuslunardi requested changes

2021-04-06 12:01 UTC, viniciuslunardi commented on Controladores/ControladorFuncionario.py
> +                pix = values[6]
eu acho que pix não faz mt sentido mercia
primeiro q, todos os alunos deveriam ter uma chave pix, o que já é inviável no mundo real
segundo que, acho que não precisamos alterar esse fluxo aqui pq decidimos deixar a classe ContaBancaria, então o cadastro de funcionário vai criar uma instancia de conta bancaria também

2021-04-06 12:01 UTC, viniciuslunardi commented on Controladores/ControladorFuncionario.py
> +                codigo_usuario = codigo_usuario
?

2021-04-06 12:01 UTC, viniciuslunardi commented on Controladores/ControladorFuncionario.py
> +                                    new = Gerente(codigo, senha, nome, cpf, data_nasc, email, pix, carga_horaria,
new Recepcionista

2021-04-06 14:29 UTC, merciasm commented on Controladores/ControladorFuncionario.py
> +                codigo_usuario = codigo_usuario
ops, resquicios do rename, vou consertar

2021-04-06 14:29 UTC, merciasm commented on Controladores/ControladorFuncionario.py
> +                                    new = Gerente(codigo, senha, nome, cpf, data_nasc, email, pix, carga_horaria,
boa

2021-04-06 14:30 UTC, merciasm commented on Controladores/ControladorFuncionario.py
> +                pix = values[6]
`todos os alunos deveriam ter uma chave pix`, nao, pq o pix se refere a conta bancaria para transacoes e isso é só relacionado aos funcionarios, nao tem nada a ver com alunos.

2021-04-06 14:32 UTC, merciasm commented on Controladores/ControladorFuncionario.py
> +                pix = values[6]
no mundo real seria dificil pedir o pix de todos os funcionarios? Creio q nao, mas mesmo que fosse, assim como a regra de nao aceitar pagamentos parciais, é uma simulacao, entao nao vejo problemas em relacao a isso

2021-04-06 14:33 UTC, merciasm commented on Controladores/ControladorFuncionario.py
> +                pix = values[6]
`acho que não precisamos alterar esse fluxo aqui pq decidimos deixar a classe ContaBancaria,`, eu nao lembro se temos alguma operacao em cima de Conta Bancaria, assim como vc mesmo tinha falado anteriormente. A gente manteve a classe p organizar melhor o codigo se me recordo bem, se usarmos o pix nesse caso, ai n precisariamos mais da classe ContaBancaria.
A nao ser q a gente fosse fazer alguma operacao em cima dessa conta

2021-04-06 14:35 UTC, merciasm commented on Controladores/ControladorFuncionario.py
> +                pix = values[6]
eu acho q simplifica as coisas usar o pix, é melhor do que tirar o parametro, melhor q deixar ele só com um numero e mais simples do que adicionar outra classe.
Além do mais, mais simples de escrever no diagrama, a gente só tem que tirar a classe ContaBancaria 😄

2021-04-07 01:39 UTC, merciasm commented
consegui consertar o alterar q tava com bug, era a ordem dos parametros nas classes abstratas q estavam diferente

2021-05-05 04:44 UTC, merged